Public-Health-Scotland/COVID-19-Publication-Dashboard

- shiny_app/contact_tracing_data_tab.R
- shiny_app/contact_tracing_tab.R
- shiny_app/functions_server.R
- shiny_app/global.R
- shiny_app/server.R
- shiny_app/setting_tab.R
- shiny_app/summary_tab.R
- shiny_app/ui.R
> new tab for settings.

- app_data_preparation.R
- shiny_app/care_home_data_tab.R
- shiny_app/data_tab.R
- shiny_app/functions_server.R
- shiny_app/global.R
- shiny_app/server.R
- shiny_app/setting_tab.R
- shiny_app/summary_tab.R
- shiny_app/ui.R
Added Care Home tab, 
updated text, 
added drop down in the navbar for contact tracing tabs
> Am changes

- shiny_app/global.R
- shiny_app/mtu_tab.R
- shiny_app/server.R
- shiny_app/ui.R
Add tab covering data on targeted community testing
> Targeted community testing

- Dashboard Data Transfer/dashboard_data_transfer.R
- Dashboard Data Transfer/data_transfer_functions.R
- shiny_app/quarantine_tab.R
- shiny_app/summary_tab.R
Suggestions for alternative filenames are given to the user if the specific data file name can't be found.
> Alternative filenames

- shiny_app/ui.R
Making sure the date for the previous week on the travel tab is updated.
> Make date displayed for travel tab dynamic

- Dashboard Data Transfer/Transfer scripts/transfer_NHS24community.R
- Dashboard Data Transfer/Transfer scripts/transfer_SAS.R
- Dashboard Data Transfer/Transfer scripts/transfer_admissions.R
- Dashboard Data Transfer/Transfer scripts/transfer_carehomes.R
- Dashboard Data Transfer/Transfer scripts/transfer_cases.R
- Dashboard Data Transfer/Transfer scripts/transfer_ethnicity.R
- Dashboard Data Transfer/Transfer scripts/transfer_labdata.R
- Dashboard Data Transfer/data_transfer_functions.R
Allow alternative filenames when reading csvs and single excel sheets as well as multiple excel sheets.
> Give alternative filenames when reading all input files

- Dashboard Data Transfer/Transfer scripts/transfer_LFD.R
- Dashboard Data Transfer/data_transfer_functions.R
- shiny_app/global.R
> Remove incomplete data entries and update LFT date

- Dashboard Data Transfer/Transfer scripts/transfer_cases.R
- app_data_preparation.R
- shiny_app/data_tab.R
- shiny_app/global.R
here's the updated code. Hopefully all ok - I'm the least confident about the global script update and whether I'm missing anywhere to add more code?
> New Data Table Prop Adm Age Grp

- Dashboard Data Transfer/Transfer scripts/transfer_carehomes.R
- Dashboard Data Transfer/Transfer scripts/transfer_cases.R
- shiny_app/functions_tables.R
1. Care homes transfer was erroring 
2. Proportion of weekly cases admitted to hospital by age group had unwanted index row
> Fix some bugs with data transfer scripts

- shiny_app/summary_tab.R
Comment requested by Scottish Ambulance Service.
> Add comment from SAS on data

- shiny_app/global.R
App wouldn't deploy to server because of explicit filepath.
> Fix deployment bug 

- Dashboard Data Transfer/Transfer scripts/transfer_labdata.R
> Make sure SIMD1 not cut off for labdata

- Dashboard Data Transfer/Transfer scripts/transfer_carehomes.R
- app_data_preparation.R
> Make sure Ayrshire & Arran included in care homes table

- shiny_app/lft_demo_tab.R
> Correct age group order for LFD demo barchart

- Dashboard Data Transfer/Transfer scripts/transfer_admissions.R
- Dashboard Data Transfer/Transfer scripts/transfer_ethnicity.R
- Dashboard Data Transfer/dashboard_data_transfer.R
- shiny_app/functions_server.R
- shiny_app/summary_tab.R
- shiny_app/ui.R
Categories for ethnicity data have changed so the transfer script has been amended, and the ethnicity graph has been updated to accommodate this.
> Updating dashboard for new ethnicity upload

- Dashboard Data Transfer/Transfer scripts/transfer_SAS.R
- shiny_app/summary_tab.R
- shiny_app/ui.R
- Changes made by @rubenv95 last week
- New paragraphs about hospital admissions
> Update dashboard info text

- Dashboard Data Transfer/Transfer scripts/transfer_admissions.R
- shiny_app/functions_server.R
1. Hospital admissions graph displaying NAs instead of 0s
2. Hospital admissions age/sex breakdown missing Total
3. SAS all and NHS Inform graphs not displaying
1. Replace NA with 0 at data transfer stage
2. Found one individual with age set to NA. Created new "unknown" age category to accommodate and prevent all Totals adding up to NA
3. Needed to return graph in plot_singletrace_chart function
> Fix bugs before PRA deployment

- shiny_app/summary_tab.R
- shiny_app/ui.R
Changes to case definition paragraphs.
> Case definition

- Dashboard Data Transfer/Transfer scripts/transfer_vaccinecert.R
- Dashboard Data Transfer/dashboard_data_transfer.R
- app_data_preparation.R
- shiny_app/global.R
- shiny_app/server.R
- shiny_app/ui.R
- shiny_app/vaccine_tab.R
Addresses #74 
Added new vaccine tab with cumulative data table and information with links.
> Add vaccine tab

- shiny_app/ui.R
Include information about vaccine certification tab in the introduction tab.
> Add vaccine certification to intro tab

- Dashboard Data Transfer/data_transfer_functions.R
Also split on spaces to improve finding keywords to locate files with slightly different names.
> Improve finding files

- shiny_app/summary_tab.R
> Notes added to NHS24 and Assessment Hubs tabs

- Dashboard Data Transfer/Transfer scripts/transfer_LFD.R
- app_data_preparation.R
- shiny_app/global.R
- shiny_app/lfd_tab.R
- shiny_app/ui.R
adding LFD test group and a corresponding table, have checked that transfer_LFD.R and app_data_preparation.R run without error. I think there's an error in lfd_tab.R (saying it can't recognise "output"?), either that or I've missed something in ui.R, will pick up in the morning as think I need to look at it with fresh eyes but you might spot something I've missed!
> Lfd testgroup

- shiny_app/lfd_tab.R
- shiny_app/ui.R
> Lft testgroup percent

- app_data_preparation.R
- shiny_app/care_home_data_tab.R
- shiny_app/global.R
- shiny_app/ui.R
Added necessary code to give us new care homes testing table and associated text.
> New care homes table and graph

- Dashboard Data Transfer/Transfer scripts/transfer_LFD.R
- shiny_app/global.R
- shiny_app/ui.R
LFD - added suppression
HCW - note to say data stops
CH - slightly reworded
CH - dropped incomplete week from data table
> Minor Updates

- shiny_app/ui.R
Mostly reordering sentences and using bullet points to make things clearer and less blocky.
> Reformat text to be more readable

- app_data_preparation.R
- shiny_app/global.R
- shiny_app/ui.R
Added more suppression to Turas CH table since it seemed not to be suppressing fully. Changed to week ending Friday for CH data. Updated titles and text.
> More care homes changes.

- Dashboard Data Transfer/Transfer scripts/transfer_CT.R
- Dashboard Data Transfer/Transfer scripts/transfer_HCW.R
- Dashboard Data Transfer/Transfer scripts/transfer_ICU.R
- Dashboard Data Transfer/Transfer scripts/transfer_LFD.R
- Dashboard Data Transfer/Transfer scripts/transfer_NHS24.R
- Dashboard Data Transfer/Transfer scripts/transfer_NHS24community.R
- Dashboard Data Transfer/Transfer scripts/transfer_NHSInform.R
- Dashboard Data Transfer/Transfer scripts/transfer_SAS.R
- Dashboard Data Transfer/Transfer scripts/transfer_admissions.R
- Dashboard Data Transfer/Transfer scripts/transfer_carehomes.R
- Dashboard Data Transfer/Transfer scripts/transfer_cases.R
- Dashboard Data Transfer/Transfer scripts/transfer_commhubsassessment.R
- Dashboard Data Transfer/Transfer scripts/transfer_communitytesting.R
- Dashboard Data Transfer/Transfer scripts/transfer_ethnicity.R
- Dashboard Data Transfer/Transfer scripts/transfer_labdata.R
- Dashboard Data Transfer/Transfer scripts/transfer_los.R
- Dashboard Data Transfer/Transfer scripts/transfer_proximityapp.R
- Dashboard Data Transfer/Transfer scripts/transfer_selfhelp.R
- Dashboard Data Transfer/Transfer scripts/transfer_travel.R
- Dashboard Data Transfer/Transfer scripts/transfer_vaccinecert.R
- Dashboard Data Transfer/dashboard_data_transfer.R
- app_data_preparation.R
- shiny_app/data_tab.R
- shiny_app/functions_server.R
- shiny_app/global.R
- shiny_app/summary_tab.R
I've added one new graph for length of stay, with a dropdown for age group. The data are proportions of hospital admissions
A new data table has also been added, which only shows the percentage of LOS in each age group
> Length of Stay Graph and Table

- Dashboard Data Transfer/Transfer scripts/transfer_cases.R
- app_data_preparation.R
- shiny_app/functions_server.R
- shiny_app/global.R
- shiny_app/summary_tab.R
Fixed the age group admissions percent chart:
New read in/save out in data transfer
Added type == "cases" to the function, so can added "admission" type to change y title and tooltip
> Hosp Age Group Fix

- Dashboard Data Transfer/Transfer scripts/transfer_carehomes.R
- app_data_preparation.R
- shiny_app/care_home_data_tab.R
- shiny_app/functions_server.R
- shiny_app/ui.R
- Add data download button
- Move graph to functions_server.R
- Move loading of data to dashboard data transfer from app_data_preparation.R
> Improve Care Homes Time Series

- shiny_app/ui.R
Tiny update, if you could check and then update the code in the folder please
> Rewording CH sentence

- shiny_app/functions_server.R
- shiny_app/lfd_tab.R
added the trends by test group graph
> Lfdtrendchart sm

- shiny_app/global.R
- shiny_app/server.R
- shiny_app/tabs/lfd_demo_tab.R
- shiny_app/tabs/vaccinations_tab.R
- shiny_app/ui.R
- shiny_app/www/styles.css
> Style dashboard and add input page

- shiny_app/global.R
- shiny_app/tabs/data_tab.R
- shiny_app/tabs/summary_tab.R
- shiny_app/ui.R
This is moving to its own separate tab on the archive as it will no longer be continued.
> Archive community hubs and assessment tab

- shiny_app/ui.R
Commenting out pages which currently have no info:
- Notes
- Healthcare workers
> Comment out blank pages

- Dashboard Data Transfer/Transfer scripts/transfer_carehomes.R
- Dashboard Data Transfer/Transfer scripts/transfer_carehomes_archive.R
- Dashboard Data Transfer/dashboard_data_transfer.R
- Separated care homes into archived and time series
- Moved archived sections to bottom of data transfer script and commented out
> Dashboard data transfer update for archived sections

- Dashboard Data Transfer/Transfer scripts/transfer_admissions.R
Using rds file rather than excel
> Read rds for CHI admissions

- app_data_preparation.R
- shiny_app/functions/functions_server.R
- shiny_app/global.R
- shiny_app/server.R
- shiny_app/tabs/lfd_demo_tab.R
- shiny_app/tabs/vaccinations_tab.R
- shiny_app/ui.R
- shiny_app/www/styles.css
- Adding lines explaining from 1 May reduced testing
- Also couple of minor edits to vaccine wastage
Closes #107
> Steady state line on graphs

- Dashboard Data Transfer/Transfer scripts/transfer_ethnicity.R
> Ethnicity date column

- shiny_app/server.R
- shiny_app/ui.R
> Unarchive vaccine certification

- Dashboard Data Transfer/Transfer scripts/transfer_carehomes_sg.R
- Dashboard Data Transfer/dashboard_data_transfer.R
- app_data_preparation.R
- shiny_app/functions/functions_tables.R
- shiny_app/global.R
- shiny_app/server.R
- shiny_app/tabs/populations_of_interest_tab.R
- shiny_app/ui.R
Adding tables for SG care homes
> Add Care Homes Visitors Tables

- shiny_app/tabs/notes_tab.R
Added note provided to the vacc certification section on notes tab
> Added note to vac certification section in notes tab

- Dashboard Data Transfer/Transfer scripts/transfer_admissions.R
- shiny_app/tabs/summary_tab.R
Leaving a bigger lag in reporting due to unstable data.
> Filter admissions max date to previous Tuesday 

- Dashboard Data Transfer/dashboard_data_transfer.R
- shiny_app/functions/functions_server.R
Bar chart rather than line chart
NB also tidied up the data transfer script
> Vaccine wastage plot - update to bars

- Dashboard Data Transfer/Transfer scripts/transfer_admissions.R
- Dashboard Data Transfer/Transfer scripts/transfer_cases.R
- app_data_preparation.R
- shiny_app/functions/functions_server.R
- shiny_app/global.R
- shiny_app/tabs/data_tab.R
- shiny_app/tabs/notes_tab.R
- shiny_app/tabs/summary_tab.R
Updating filepath and filename for the new rapid files.
> New filepath for rapid files

- Dashboard Data Transfer/dashboard_data_transfer.R
- shiny_app/functions/functions_server.R
- shiny_app/tabs/data_tab.R
- shiny_app/tabs/lfd_demo_tab.R
Summary
- Added SG carehome transfer script to the data transfer 
- Adjusted default rows in LFD demographics age sex table
- Fixed rendering of percentages in cases SIMD table
- Fixed reinfections graph so weeks without 7 days of data will still have proportions adding up to 100%
> Changes from 28th June 2022 PRA run

- shiny_app/functions/functions_server.R
Last week of provisional data appears in grey with separate legend and tooltip
> Highlight provisional data on hospital admissions chart

- shiny_app/tabs/summary_tab.R
> ethnicity data date update

- shiny_app/ui.R
Leftover sentence when there was a testing data issue
> old sentence removed

- Dashboard Data Transfer/Transfer scripts/transfer_admissions.R
- Dashboard Data Transfer/dashboard_data_transfer.R
- shiny_app/functions/functions_tables.R
- shiny_app/tabs/notes_tab.R
- shiny_app/ui.R
Using proxy figures for health boards which haven't submitted in time. 
Using the previous week's data for those health boards to create the total figures.
> Use proxy files for RAPID data

- Dashboard Data Transfer/Transfer scripts/transfer_ethnicity.R
- shiny_app/functions/functions_tables.R
- shiny_app/tabs/summary_tab.R
updating ethnicity and fixing board table header colours
> Ethnicity&table colours cm

- shiny_app/tabs/notes_tab.R
Add a note stating the calculation for vaccine wastage
> Wastage notes

- shiny_app/functions/functions_server.R
unicode for greater than 48 hours
> unicode for greater than 48 hours

- shiny_app/tabs/notes_tab.R
- shiny_app/tabs/summary_tab.R
> Update notes page to match report

- shiny_app/global.R
- shiny_app/tabs/notes_tab.R
Adding notes explaining missing data for days in September.
> Vaccine Certification Note

- shiny_app/functions/functions_server.R
I used a test file from today in data transfer to check this works. Should be able to test too if you run app data prep.
Change the categories/factor/colours for the new LOS categories
> update los chart to new categories

- Dashboard Data Transfer/dashboard_data_transfer.R
- shiny_app/global.R
- shiny_app/tabs/data_tab.R
- shiny_app/tabs/summary_tab.R
- shiny_app/ui.R
Moved SAS to archive
Tweaked home page buttons
Updated surveillance list (to re-add SAS to surveillance but in archive)
> Archive SAS tab

- Dashboard Data Transfer/Transfer scripts/transfer_ethnicity.R
- shiny_app/tabs/summary_tab.R
When the new data comes in for 30th Nov we will need to merge this PR so the refresh date is corrected.
> Update refresh date for hospital admissions ethnicity data

- Dashboard Data Transfer/Transfer scripts/transfer_admissions.R
- Dashboard Data Transfer/dashboard_data_transfer.R
- app_data_preparation.R
- shiny_app/functions/functions_server.R
- shiny_app/global.R
- shiny_app/tabs/summary_tab.R
Adding SIMD trend chart to dashboard
> Making SIMD trend chart
